apiVersion: v1
kind: Secret
metadata:
  name: dentistdev-secrets
  namespace: dentistdev
type: Opaque
stringData:
  mysql-connection-string: "server=mysql;port=3306;database=DentistDevops;user=app;password=apppass;"
  jwt-issuer: "dentistdevops"
  jwt-key: "THIS_IS_A_LONG_JWT_TOKEN_THAT_IS_OVER_32_CHARACTERS"
