apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dentistdev

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/robryst/dentistdev-backend
    newTag: sha-${GITHUB_SHA}
  - name: ghcr.io/robryst/dentistdev-frontend
    newTag: sha-${GITHUB_SHA}
